source 'https://rubygems.org'

gem 'less', '~> 2.2.2'
gem 'middleman', '~> 3.2.0'
gem 'middleman-deploy', '~> 1.0'
gem 'rack-contrib', '~> 1.1.0'
gem 'redcarpet', '~> 2.2.2'
gem 'therubyracer', '~> 0.12.0'
